### PR TITLE
Update Item.html

### PR DESCRIPTION
**Pull request by responseinformationsdesign**
Partial has to be updated for Version 5.0 of news (No namespace fallback, dropped viewhelpers, ...)

### CODE REVIEW

**Comment by kaystrobach** [comment]
just a question, which one is now the lowest supported news version ... imho we should add this to the documentation.

**Comment by responseinformationsdesign** [comment]
I don´t know if version 4.x of extension "News system" is still supported as system requirements of version 5.x are identical to 4.x. But the example of Item.html delivered by theme_bootstrap 7.x seems to be quite old (copied from a version below 3.x). As TYPO3 7.6 is required for theme_bootstrap 7.x the news extension has at least to be 4.x. Therefore example partial should also be derived from 4.x or newer.

**Comment by kaystrobach** [comment]
could you please check wether it works with 4.x then i will do a fast merge, otherwise we need to raise the version constraint (suggestion) and have a breaking change here which will also include the raise of the version number to *7.1.x* or even *8.x* according to http://semver.org/

**Comment by responseinformationsdesign** [comment]
Just copied this new modified "Item.html" into a installation of news 4.3.0 without any problem. However the part for pre-FAL media relations (which were supported up to 4.x) is not contained in this 5.0-based partial any more. Maybe it would be better to use an cutomized version of "Item.html" of 4.3.0.

**Comment by kaystrobach** [comment]
Ok, so i will raise version number accordingly ;) thanks a lot for your effort

**Pull request merged**
